package constant

const (
	DB_HOST_POSTGRES     = "DB_HOST_POSTGRES"
	DB_USER_POSTGRES     = "DB_USER_POSTGRES"
	DB_PASSWORD_POSTGRES = "DB_PASSWORD_POSTGRES"
	DB_NAME_POSTGRES     = "DB_NAME_POSTGRES"
	DB_PORT_POSTGRES     = "DB_PORT_POSTGRES"

	GIN_ADDRESS = "GIN_ADDRESS"
	GIN_PORT    = "GIN_PORT"
)
